log4cplus.rootLogger=INFO, Console, RollingFile

log4cplus.appender.Console=log4cplus::ConsoleAppender
log4cplus.appender.Console.layout=log4cplus::PatternLayout
log4cplus.appender.Console.layout.ConversionPattern=%d{%H:%M:%S} [%t] %-5p %c - %m%n

log4cplus.appender.RollingFile=log4cplus::RollingFileAppender
log4cplus.appender.RollingFile.File=LogicSyc.log
log4cplus.appender.rollingFile.CreateDirs=true 
log4cplus.appender.rollingFile.MaxFileSize=1MB
log4cplus.appender.RollingFile.MaxBackupIndex=10
log4cplus.appender.RollingFile.layout=log4cplus::PatternLayout
log4cplus.appender.RollingFile.layout.ConversionPattern=%d{%Y-%m-%d %H:%M:%S} [%t] %-5p %c - %m%n